//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public Rent()
        {
            this.Payments = new HashSet<Payment>();
            this.Requests = new HashSet<Request>();
            this.reviewofrents = new HashSet<reviewofrent>();
        }
    
        public int id { get; set; }
        public Nullable<int> InfoId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual RentInfo RentInfo { get; set; }
        public virtual Room Room { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<reviewofrent> reviewofrents { get; set; }
    }
}
