//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInfo
    {
        public RentInfo()
        {
            this.Rents = new HashSet<Rent>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public string pic { get; set; }
    
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
