//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestinfo
    {
        public requestinfo()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
