//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewinfo
    {
        public reviewinfo()
        {
            this.Reviewofusers = new HashSet<Reviewofuser>();
        }
    
        public int id { get; set; }
        public string review { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<Reviewofuser> Reviewofusers { get; set; }
    }
}
