//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roominfo
    {
        public roominfo()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public Nullable<int> nofrooms { get; set; }
        public Nullable<int> maxmembers { get; set; }
        public Nullable<int> atfloor { get; set; }
        public Nullable<int> sqft { get; set; }
        public string zone { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
