//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.FacilitiesForRooms = new HashSet<FacilitiesForRoom>();
            this.Rents = new HashSet<Rent>();
        }
    
        public int id { get; set; }
        public Nullable<int> infoid { get; set; }
        public Nullable<int> ownerid { get; set; }
        public Nullable<int> upazilaid { get; set; }
    
        public virtual ICollection<FacilitiesForRoom> FacilitiesForRooms { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<Rent> Rents { get; set; }
        public virtual roominfo roominfo { get; set; }
    }
}
