//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.Rents = new HashSet<Rent>();
            this.Requests = new HashSet<Request>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual ICollection<Rent> Rents { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual User User { get; set; }
    }
}
