//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
            this.reviewofrents = new HashSet<reviewofrent>();
            this.Reviewofusers = new HashSet<Reviewofuser>();
            this.Reviewofusers1 = new HashSet<Reviewofuser>();
        }
    
        public int id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Cell { get; set; }
        public string Address { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> Tenantid { get; set; }
        public Nullable<int> AccId { get; set; }
        public string pic { get; set; }
    
        public virtual Auth Auth { get; set; }
        public virtual bank bank { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
        public virtual ICollection<reviewofrent> reviewofrents { get; set; }
        public virtual ICollection<Reviewofuser> Reviewofusers { get; set; }
        public virtual ICollection<Reviewofuser> Reviewofusers1 { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
