//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Chats = new HashSet<Chat>();
            this.Chats1 = new HashSet<Chat>();
            this.Owners = new HashSet<Owner>();
            this.reviewofrents = new HashSet<reviewofrent>();
            this.Reviewofusers = new HashSet<Reviewofuser>();
            this.Reviewofusers1 = new HashSet<Reviewofuser>();
            this.Tenants = new HashSet<Tenant>();
        }
    
        public int id { get; set; }
        public int PropertiesId { get; set; }
        public int AuthId { get; set; }
        public int ContactId { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<Chat> Chats1 { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
        public virtual ICollection<reviewofrent> reviewofrents { get; set; }
        public virtual ICollection<Reviewofuser> Reviewofusers { get; set; }
        public virtual ICollection<Reviewofuser> Reviewofusers1 { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
        public virtual UserAuth UserAuth { get; set; }
        public virtual UserContact UserContact { get; set; }
        public virtual UserProperty UserProperty { get; set; }
    }
}
